# Generated by Django 5.1.1 on 2024-10-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_status_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
